name: 'windows-latest'

on:
  push:
    branches:
      - minor

jobs:
  windows-latest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build . --config Release
      - run: "./Debug/hello_test.exe"
      - run: cpack
      